outfile:main.o add_begin.o count.o save.o print.o
	cc -c main.c add_begin.c count.c save.c print.c

outfile:
main.o:main.c	
	cc -c main.c
add_begin.o:add_begin.c
	cc -c add_begin.c
count.o:count.c
	cc -c count.c
save.o:save.c
	cc -c save.c
print.o:print.c
	cc -c print.c

